version: "3"

services:
  # Web service with cookies tracking
  cookies:
    build: ./
    image: cookies
    container_name: cookies
    hostname: cookies
    ports:
        - "5000:5000"
        - "8080:8080"
    restart: unless-stopped

