version: "3"

services:
  # Web service with phishing
  phishing:
    build: ./
    image: phishing
    container_name: phishing
    hostname: phish
    ports:
        - "5000:5000"
        - "5001:5001"
    restart: unless-stopped

