version: "3"

services:

  # Python3  
  poodle:
    build: 
      context: ./
      dockerfile: ./python3-alone/Dockerfile
    container_name: python-poodle
    hostname: poodle
    ports:
     - "8080:80"
    stdin_open: true
    tty: true

  # Python3 on alpine
  poodle2:
    image: python:3.9-alpine3.13
    container_name: python-alpine
    hostname: poodle2
    volumes:
       - ./code:/poolde
    stdin_open: true
    tty: true