version: "3"

services:
  # Web service with phishing
  phishing:
    build: ./
    container_name: phishing
    hostname: fish
    ports:
        - "5000:5000"
        - "5001:5001"
        - "443:443"
    restart: unless-stopped

