version: "3"

services:
  # Web service with phishing
  phishing:
    build: ./
    image: phishing
    container_name: phishing
    hostname: phish
    ports:
        - "9000:5000"
    restart: unless-stopped

