FROM fedora

RUN dnf -y install gnupg pinentry && \
dnf -y install tigervnc tigervnc-server && \
dnf -y install ipsec-tools && \
dnf -y install openssl openvpn && \
dnf -y install net-tools tcpdump && \
dnf -y install vim