FROM fedora

RUN dnf -y install gnupg && \
dnf -y install tigervnc-server && \
dnf -y install ipsec-tools && \
dnf -y install install openssl openvpn && \
dnf -y install install tcpdump && \
dnf -y install vim