version: "3"

# networks:
#   lab:
#     ipam:
#       config:
#         - subnet: 10.0.103.0/24

services:
  # Linux for ciphers
  sec-linux:
    build: ./
    container_name: ciphers
    hostname: sec-linux
    volumes:
      - ./local_data:/docker_data    

  # Web server with https
  web-server:
    build: ./web_server
    container_name: web
    hostname: web
    restart: always
    # networks:
    #   lab:
    #     ipv4_address: 10.0.103.2
    ports:
      - "8080:80/tcp"
      - "443:443/tcp"
