# Docker Version: 18.09
# Docker Compose Version: 3.7

version: "3"

services:
    fedora:
        build: ./server_config
        container_name: client1
        #volumes:
        #  - /tmp:/home/student
        ports:
          - "5000:22"
        command: /sbin/init
    web:
        build: ./client_config
        container_name: web
        ports:
          - "80:80"
          - "443:443"
