FROM ubuntu

RUN apt-get update \
    && apt-get install -y --force-yes --no-install-recommends supervisor \
        gcc zsh sudo vim-tiny wget libc-dev

RUN useradd -ms /bin/bash student

# USER student
# WORKDIR /home/student

ADD ./c_programs  /home/student/

