version: "3"

services:

  # Web service: Apache + Fedora
  web-server:
    build: ./web
    container_name: web-server
    hostname: web
    ports:
     - "80:80"
    restart: unless-stopped

  # Client
  client:
    build: ./client
    container_name: client
    hostname: client
    stdin_open: true
    tty: true

  # Attacker using ping and curl to web-server
  attacker:
    build: ./attacker
    container_name: attacker
    hostname: attacker
    stdin_open: true
    tty: true

  # # Firewall service: iptables
  # firewall:
  #   build: ./iptables
  #   container_name: iptables
  #   hostname: firewall
  #   ports:
  #     - "8388:8388"
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

