version: "3"

services:

  # Web service: Apache + Fedora
  web-server:
    build: ./web-fedora
    container_name: web-server
    hostname: web
    ports:
     - "80:80"
    cap_add:
     - NET_ADMIN
    privileged: true 
    restart: unless-stopped

  # Client
  client:
    build: ./client
    container_name: client
    hostname: client
    stdin_open: true
    tty: true

  # Attacker using ping and curl to web-server
  attacker-1:
    build: ./attacker
    container_name: attacker-1
    hostname: attacker-1
    stdin_open: true
    tty: true

  # Attacker using ping and curl to web-server
  attacker-2:
    build: ./attacker
    container_name: attacker-2
    hostname: attacker-2
    stdin_open: true
    tty: true
