version: "3"

services:

  # Web service with https
  web-server:
    build: ./web-server
    container_name: web-server-https
    hostname: web
    ports:
     - "80:80"
    cap_add:
     - NET_ADMIN
    privileged: true 
    restart: unless-stopped

  # Attacker using ping and curl to web-server
  attacker:
    image: metasploit-framework
    container_name: metasploit-attacker
    hostname: attacker
    stdin_open: true
    tty: true

 