version: "3"

services:

  # Web service with https
  web-server:
    build: ./web-server
    container_name: web-server-https
    hostname: web
    ports:
     - "8443:443"
    privileged: true 
    restart: unless-stopped

  # Attacker using nmap and metasploit
  attacker:
    image: metasploitframework/metasploit-framework
    container_name: metasploit-attacker
    hostname: attacker
    stdin_open: true
    tty: true

 