version: "3"

services:

  # Web service with https
  web-server:
    build: ./web-server
    container_name: web-server-https
    hostname: web
    ports:
     - "8443:443"
    privileged: true 
    restart: unless-stopped

  # Scanner using nmap
  scanner:
    image: instrumentisto/nmap
    container_name: nmap-scanner
    hostname: scanner
    stdin_open: true
    tty: true