version: "3"

services:

  # Web service with https
  web-server:
    build: ./web-server
    container_name: web-server-https
    hostname: web
    ports:
     - "8443:443"
    privileged: true 
    restart: unless-stopped


  # Attacker using nmap and metasploit
  attacker:
    image: metasploitframework/metasploit-framework
    container_name: metasploit-attacker
    hostname: attacker
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    links:
      - db
    ports:
      - 4444:4444
    volumes:
      - $HOME/.msf4:/home/msf/.msf4
    stdin_open: true
    tty: true

  db:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  volumes:
    pg_data:
      driver: local
 