version: "3"

services:

  # Web service 
  web-server:
    build: ./web-server
    container_name: web-server
    hostname: web
    ports:
     - "8080:80"
    privileged: true 
    restart: unless-stopped
