version: '3'
services:
  xss-demo-database:
    image: 'mysql:5'
    container_name: xss-demo-database
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
      - MYSQL_DATABASE=xss_db
      - MYSQL_USER=xss_db_user
      - MYSQL_PASSWORD=password1234
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  xss-demo:
    container_name: xss-demo
    volumes:
      - './src/:/var/www/html/'
    build: .
    ports:
      - '80:80'
