version: "3"

networks:
  lab:
    name: kerberos-network
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.103.0/24

services:
  kdc-server:
    build: ./kdc-server
    container_name: kdc-server
    hostname: kdc-server
    restart: always
    privileged: true
    networks:
      lab:
        ipv4_address: 10.0.103.2
    volumes:
      - /dev/urandom:/dev/random
    ports:
      - "749:749"
      - "88:88/udp"  



  # kdc-ssh-server
  kdc-ssh-server:
    build: ./kdc-ssh-server
    container_name: kdc-ssh-server
    hostname: kdc-ssh-server
    restart: always
    privileged: true
    networks:
      lab:
        ipv4_address: 10.0.103.3
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
    ports:
      - "749:749"
      - "88:88/udp"
      - "2222:22"

