version: "3"

networks:
  lab:
    ipam:
      config:
        - subnet: 172.17.0.0/24

services:
  ipsec-server:
    build: ./server
    container_name: server
    hostname: ipsec-server
    restart: always
    privileged: true
    # networks:
    #   lab:
    #     ipv4_address: 172.17.0.3
    volumes:
      - ./server:/data    

  # IPsec client
  ipsec-client:
    build: ./client
    container_name: client
    hostname: ipsec-client
    restart: always
    privileged: true
    # networks:
    #   lab:
    #     ipv4_address: 172.17.0.2
    volumes:
      - ./client:/data   

