version: "3"

networks:
  lab:
    name: auth-network
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.103.0/24

services:
  ssh-server:
    build: ./ssh_server
    container_name: ssh-server
    hostname: ssh-server
    restart: always
    privileged: true
    networks:
      lab:
        ipv4_address: 10.0.103.2
    # volumes:
    #   - ./ssh_server:/s_keys    

  # ssh client
  ssh-client:
    build: ./ssh_client
    container_name: ssh-client
    hostname: ssh-client
    restart: always
    privileged: true
    networks:
      lab:
        ipv4_address: 10.0.103.3
    volumes:
      - ./ssh_client/pub_keys:/c_keys   

